import java.io.*;
import java.net.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class FarmServer {
	    public static void main(String[] args) {
	    	        int port = 5000;
	    	                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");

	    	                        try (ServerSocket serverSocket = new ServerSocket(port)) {
	    	                        	            System.out.println("--- PHASE 6: STRUCTURED SERVER ACTIVE ---");

	    	                        	                        while (true) {
	    	                        	                        	                try (Socket clientSocket = serverSocket.accept()) {
	    	                        	                        	                	                    BufferedReader in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
	    	                        	                        	                	                                        String rawData = in.readLine();

	    	                        	                        	                	                                                            if (rawData != null) {
	    	                        	                        	                	                                                            	                        // Splitting the raw CSV string
	    	                        	                        	                	                                                            	                                                String[] p = rawData.split(",");
	    	                        	                        	                	                                                            	                                                                        String time = dtf.format(LocalDateTime.now());

	    	                        	                        	                	                                                            	                                                                                                // THE 2% TASK: Creating the Object
	    	                        	                        	                	                                                            	                                                                                                                        FarmReport report = new FarmReport(p[0], p[1], p[2], p[3], time);

	    	                        	                        	                	                                                            	                                                                                                                                                // Print the structured version using toString()
	    	                        	                        	                	                                                            	                                                                                                                                                                        System.out.println("OBJECT CREATED: " + report.toString());

	    	                        	                        	                	                                                            	                                                                                                                                                                                                // Log to file
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        try (PrintWriter logger = new PrintWriter(new BufferedWriter(new FileWriter("farm_log.txt", true)))) {
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                            logger.println(report.toString());
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                    }
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                        }
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        } catch (IOException e) {
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                    System.out.println("Client Error: " + e.getMessage());
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                    }
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                                }
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                                        } catch (IOException e) {
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                                        	            System.out.println("Server Error: " + e.getMessage());
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                                        	                    }
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                                        	                        }
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                                        	                        }
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                                        	                        
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                        	                                                     
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                        	                                                                                     
	    	                        	                        	                	                                                            	                                                                                                                                                                                                                     
	    	                        	                        	                	                                                         
	    	                        	                        	            
	    	                        	                     
	    	                
	
