import java.io.*;
import java.net.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class FarmServer {
	    public static void main(String[] args) {
	    	        int port = 5000;
	    	                // Formatter for a clean timestamp
	    	                        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");

	    	                                try (ServerSocket serverSocket = new ServerSocket(port)) {
	    	                                	            System.out.println("--- PHASE 5: SERVER WITH MEMORY ACTIVE ---");
	    	                                	                        System.out.println("Listening on port " + port + "...");

	    	                                	                                    while (true) {
	    	                                	                                    	                try (Socket clientSocket = serverSocket.accept()) {
	    	                                	                                    	                	                    BufferedReader in = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
	    	                                	                                    	                	                                        String rawData = in.readLine();

	    	                                	                                    	                	                                                            if (rawData != null) {
	    	                                	                                    	                	                                                            	                        String timestamp = dtf.format(LocalDateTime.now());
	    	                                	                                    	                	                                                            	                                                String logEntry = timestamp + " | " + rawData;

	    	                                	                                    	                	                                                            	                                                                        // 1. Show it in the terminal
	    	                                	                                    	                	                                                            	                                                                                                System.out.println("LOGGED: " + logEntry);

	    	                                	                                    	                	                                                            	                                                                                                                        // 2. SAVE TO FILE (The 2% Milestone)
	    	                                	                                    	                	                                                            	                                                                                                                                                // 'true' means append to the file rather than overwriting it
	    	                                	                                    	                	                                                            	                                                                                                                                                                        try (PrintWriter logger = new PrintWriter(new BufferedWriter(new FileWriter("farm_log.txt", true)))) {
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                            logger.println(logEntry);
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                    }
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                        }
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        } catch (IOException e) {
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                    System.out.println("Connection error: " + e.getMessage());
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                    }
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                                }
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                                        } catch (IOException e) {
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                                        	            System.out.println("Server Error: " + e.getMessage());
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                                        	                    }
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                                        	                        }
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                                        	                        }
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                                        	                        
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                        	                                                     
	    	                                	                                    	                	                                                            	                                                                                                                                                                        	                                                                                    
	    	                                	                                    	                	                                                            	                                                                                                                                                                      
	    	                                	                                    	                	                                                         
	    	                                	                                    	            
	    	                                	                                 
	    	                            
	 
